### ISSUE TITLE
Handle only messages in thread. Do not handle if not in thread

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/chatgpt-azure-discord-bot#1]

**Comment by LiKissDmd** [comment]
I take it

**Comment by LiKissDmd** [comment]
https://www.npmjs.com/package/@deep-foundation/chatgpt-azure-discord-bot/v/2.0.0-dev.0
I have made required changed. I need review

**Comment by FreePhoenix888** [comment]
We misunderstod `hasThread` description: https://github.com/discordjs/discord.js/issues/10157
We should use `message.channelId` to [get channel](https://discord.com/developers/docs/resources/channel#get-channel) info and then [check its type](https://discord.com/developers/docs/resources/channel#channel-object-channel-types)

**Comment by FreePhoenix888** [comment]
The same links but for discordjs:
https://discord.js.org/docs/packages/discord.js/14.14.1/ChannelManager:Class#fetch
https://discord.js.org/docs/packages/discord.js/14.14.1/Channel:TypeAlias

**Comment by FreePhoenix888** [comment]
```ts
      const channelManager = discordClient.channels;
      const channel = await channelManager.fetch(message.channelId)
      const publicThreadTypeNumber = 11;
      const privateThreadTypeNumber = 12;
      console.log({channel})
      const isInThread = channel.type === publicThreadTypeNumber || channel.type === privateThreadTypeNumber
      console.log({isInThread})
      if (message.content.includes(mentionPrefix) && !message.author.bot && isInThread) {
```

**Comment by FreePhoenix888** [comment]
I have added channel check in 2.0.0-dev.1
